---
- name: Unpacking uwsgi...
  unarchive: src={{ uwsgi_download_url }} dest=/tmp copy=no
  become: false

- name: Pushing uwsgi build configs...
  template: src=uwsgibuild.ini dest=/tmp/uwsgi-{{ uwsgi_version }}/buildconf/uwsgibuild.ini
  become: false

- name: Building uwsgi...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python2.7 uwsgiconfig.py --build uwsgibuild
  become: false

- name: Building python2 plugins...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python2.7 uwsgiconfig.py --plugin plugins/{{item}} uwsgibuild {{item}}2
  become: false
  with_items:
    - python
    - greenlet
    - gevent

- name: Building python3 plugins...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python3 uwsgiconfig.py --plugin plugins/{{item}} uwsgibuild {{item}}3
  become: false
  with_items:
    - python
    - asyncio

- name: Building python3 greenlet...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python3 uwsgiconfig.py --plugin plugins/{{item}} uwsgibuild {{item}}3
  become: false
  with_items:
    - gevent
    - greenlet
  when: >
      (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 14)
      or (ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 8)

- name: Building other uwsgi plugins
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python uwsgiconfig.py --plugin plugins/{{item}} uwsgibuild {{item}}
  become: false
  environment:
      UWSGICONFIG_PHPLIBDIR: /usr/lib/php5
  with_items:
    - php
    - lua

- name: Building other uwsgi plugins
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python uwsgiconfig.py --plugin plugins/{{item}} uwsgibuild {{item}}
  become: false
  environment:
      UWSGICONFIG_RUBYPATH: ruby
  with_items:
    - rack
    - rbthreads
    - fiber
  when: not (ansible_os_family == "RedHat" and ansible_lsb.major_release|int < 7)

- name: Making sure uwsgi plugin directory exists...
  file: state=directory path={{ uwsgi_lib_dir }} mode=0755

- name: Installing uwsgi...
  command: chdir=/tmp/uwsgi-{{ uwsgi_version }} install -s -m 0755 uwsgi /usr/local/bin/uwsgi
  notify: restart the uwsgi emperor

- name: Installing uwsgi plugins...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} install -s -m 0755 *.so {{ uwsgi_lib_dir }}
  notify: restart the uwsgi emperor

- name: Remove source files...
  file: dest=/tmp/uwsgi-{{ uwsgi_version }} state=absent
